[package]
name = "redstone-rust-sdk"
version = "0.1.2"
edition = "2021"
description = "RedStone Rust SDK"
license-file = "LICENSE"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitmaps = "3.2.0"
ink_env = "3.4.0"
