[package]
name = "redstone-rust-sdk"
version = "0.1.0"
edition = "2021"
description = "RedStone Rust SDK"
license-file = "LICENSE"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
